version: '2.3'
services:
  ##### the develop image you've build
  ### don't forget to open ports for your app
  dev-image:
    image: acerja2/powergrid-dev:latest
    privileged: true
    container_name: devenv
    runtime: nvidia
# mapping your project folder (.) to /home/develop/project    
    volumes:
      - "../:/root/code"
      
networks:
  default:
    external:
      name: bridge